# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: tstone-1.tpdf
PackageVersion: 26.10.12
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/tstone-1/tpdf/releases/download/v26.10.12/tpdf_26.10.12_x64-setup.exe
  InstallerSha256: F548A70453E44B675E1A134E4C8E0334457EA97FB1CA6D40BFC7BEAD1E118DD2
ManifestType: installer
ManifestVersion: 1.12.0
